/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'message' : string,
  'timestamp' : bigint,
  'requesterName' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface MCPlan {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'price' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type RequestStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'seen' : null };
export interface Stats {
  'activePlans' : bigint,
  'pendingRequests' : bigint,
  'pageVisits' : bigint,
  'totalRequests' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdatePlan' : ActorMethod<
    [string, string, string, string, Array<string>, boolean],
    undefined
  >,
  'deletePlan' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActivePlans' : ActorMethod<[], Array<MCPlan>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllRequests' : ActorMethod<[], Array<CommunityRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getPageVisits' : ActorMethod<[], bigint>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementVisits' : ActorMethod<[], undefined>,
  'initDefaultPlans' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitRequest' : ActorMethod<[string, string], undefined>,
  'updateRequestStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];